'***** Read Field Type Choices
REDIM TypCh$(22)
REDIM TypCh(22)

TypCh$(1) = "String                  "
TypCh(1) = 1
TypCh$(2) = "Proper String " + CHR$(34) + "Ul Ull" + CHR$(34) + "  "
TypCh(2) = 23
TypCh$(3) = "Upper Case String       "
TypCh(3) = 2
TypCh$(4) = "Numeric String          "
TypCh(4) = 16
TypCh$(5) = "Multi Line Text         "
TypCh(5) = 17
TypCh$(6) = "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ "
TypCh$(7) = "Logical (2 Choices)     "
TypCh(7) = 14
TypCh$(8) = "Integer                 "
TypCh(8) = 3
TypCh$(9) = "Long Integer            "
TypCh(9) = 18
TypCh$(10) = "Single Precision        "
TypCh(10) = 4
TypCh$(11) = "Double Precision        "
TypCh(11) = 5
TypCh$(12) = "Currency $              "
TypCh(12) = 10
TypCh$(13) = "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ "
TypCh$(14) = "Date MM-DD-YYYY         "
TypCh(14) = 6
TypCh$(15) = "Date DD-MM-YYYY         "
TypCh(15) = 19
TypCh$(16) = "Phone Number            "
TypCh(16) = 7
TypCh$(17) = "Zip Code                "
TypCh(17) = 9
TypCh$(18) = "Social Security #       "
TypCh(18) = 8
TypCh$(19) = "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ "
TypCh$(20) = "Relational...           "
TypCh(20) = 11
TypCh$(21) = "Multiple Choice Array   "
TypCh(21) = 22
TypCh$(22) = "Command Button          "
TypCh(22) = 24

